export const EVENTS = {
    'GRAB_GIFT_VN': 'GRAB_GIFT_VN',
    'GRAB_GIFT_KR': 'GRAB_GIFT_KR',
}
export const EVENT_STATUS = {
    WIN: 'WIN',
    MAX_WINNER: 'MAX_WINNER',
    CLOSE: 'CLOSE',
    ALREADLY_WIN: 'ALREADLY_WIN',
    NOT_COMPLETE: 'NOT_COMPLETE'
}